# Generated by Django 4.2.3 on 2023-07-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstringstranslations',
            name='string',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
