# Generated by Django 4.2.3 on 2023-07-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_alter_applicationstringstranslations_string'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationStrings',
            new_name='ApplicationString',
        ),
        migrations.RenameModel(
            old_name='ApplicationStringsTranslations',
            new_name='ApplicationStringsTranslation',
        ),
    ]
