# Generated by Django 4.2.3 on 2023-07-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_rename_applicationstrings_applicationstring_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applicationstringstranslation',
            constraint=models.UniqueConstraint(fields=('translation_string', 'language'), name='unique_translation_string_language'),
        ),
    ]
