# Generated by Django 4.2.3 on 2023-08-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0007_alter_language_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstringstranslation',
            options={'ordering': ['translation_string__formatjs_id', 'language__code']},
        ),
        migrations.AddField(
            model_name='applicationstringstranslation',
            name='is_special_char',
            field=models.BooleanField(default=False),
        ),
    ]
