# Generated by Django 4.2.3 on 2023-08-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0008_alter_applicationstringstranslation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstringstranslation',
            name='is_special_char',
        ),
        migrations.AddField(
            model_name='applicationstring',
            name='is_special_char',
            field=models.BooleanField(default=False),
        ),
    ]
