# Generated by Django 4.2.3 on 2023-08-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0010_autopushlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopushlog',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
