# Generated by Django 4.2.3 on 2023-08-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0012_manualpushrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphqlEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraphqlEnumValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('base_enum_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translate.graphqlenumvalue')),
                ('enum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.graphqlenum')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='manualpushrequest',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='GraphqlEnumValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('string', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('enum_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.graphqlenumvalue')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
