# Generated by Django 4.2.3 on 2023-08-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0013_graphqlenum_graphqlenumvalue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphqlenumvalue',
            old_name='value',
            new_name='name',
        ),
    ]
