# Generated by Django 4.2.3 on 2023-08-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0015_remove_graphqlenumvalue_base_enum_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphqlenum',
            name='values',
            field=models.ManyToManyField(to='translate.graphqlenumvalue'),
        ),
        migrations.DeleteModel(
            name='GraphqlEnumValueAssignment',
        ),
    ]
