# Generated by Django 4.2.3 on 2023-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0017_alter_manualpushrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpushrequest',
            name='target_type',
            field=models.CharField(choices=[('application_string', 'Application String'), ('graphql_enum_value', 'Graphql Enum Value')], default='application_string', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(choices=[('en-US', 'English'), ('fr-CA', 'French (Canada)'), ('fa-IR', 'Persian (Iran)'), ('he-IL', 'Hebrew'), ('pt-BR', 'Portuguese (Brazil)')], max_length=5, unique=True),
        ),
    ]
