# Generated by Django 4.2.3 on 2023-08-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0019_manualtranslaterequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualpushrequest',
            options={'verbose_name': 'Manually create pull request', 'verbose_name_plural': 'Manual;y create pull request'},
        ),
        migrations.AlterModelOptions(
            name='manualtranslaterequest',
            options={'verbose_name': 'Manually run auto translate', 'verbose_name_plural': 'Manually run auto translate'},
        ),
        migrations.AddField(
            model_name='autopushlog',
            name='target_type',
            field=models.CharField(choices=[('application_string', 'Application String'), ('graphql_enum_value', 'Graphql Enum Value')], default='application_string', max_length=100),
        ),
    ]
