# Generated by Django 4.2.3 on 2023-08-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0020_alter_manualpushrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formatjs_id', models.CharField(max_length=100, unique=True)),
                ('default_message', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='manualpushrequest',
            options={'verbose_name': 'Manually create pull request', 'verbose_name_plural': 'Manually create pull request'},
        ),
        migrations.CreateModel(
            name='CustomKeyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('string', models.CharField(blank=True, default='', max_length=255)),
                ('custom_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.customkeys')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.language')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customkeytranslation',
            constraint=models.UniqueConstraint(fields=('custom_key', 'language'), name='unique_custom_key_language'),
        ),
    ]
