# Generated by Django 4.2.3 on 2023-08-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0021_customkeys_alter_manualpushrequest_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomKeys',
            new_name='CustomKey',
        ),
    ]
