# Generated by Django 4.2.3 on 2023-08-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0022_rename_customkeys_customkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customkey',
            name='default_message',
        ),
    ]
