# Generated by Django 4.2.3 on 2023-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translate", "0024_alter_applicationstring_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphqlenumvaluetranslation",
            name="string",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
