# Generated by Django 4.2.3 on 2023-08-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translate", "0025_alter_graphqlenumvaluetranslation_string"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customkeytranslation",
            options={
                "verbose_name": "custom key translation",
                "verbose_name_plural": "3. Custom Key Translations",
            },
        ),
        migrations.AddField(
            model_name="customkeytranslation",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
