# Generated by Django 4.2.7 on 2024-01-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0027_duplicatestring_alter_customkey_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(choices=[('en-US', 'English'), ('fr-CA', 'French (Canada)'), ('fa-IR', 'Persian (Iran)'), ('he-IL', 'Hebrew'), ('pt-BR', 'Portuguese (Brazil)'), ('es-ES', 'Spanish (Spain)')], max_length=5, unique=True),
        ),
    ]
